[phases.setup]
nixPkgs = ["nodejs-16_x"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --prefer-offline"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"